export const GET_MOVIES_REQUESTED = "GET_MOVIES_REQUESTED";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";
export const DELETE_MOVIE = "DELETE_MOVIE";

export const GET_MOVIE_DETAILS_REQUESTED = "GET_MOVIE_DETAILS_REQUESTED";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAILED = "GET_MOVIE_DETAILS_FAILED";